[package]
name = "highlights"
version = "2.0.0"
authors = ["ThatsNoMoon <git@thatsnomoon.dev>"]
repository = "https://github.com/ThatsNoMoon/highlights"
license = "OSL-3.0"
edition = "2021"

[features]
default = ["bot", "monitoring", "reporting"]
bot = [
    "regex",
    "indoc",
    "serde_json",
    "serenity/builder",
    "serenity/cache",
    "serenity/client",
    "serenity/collector",
    "serenity/gateway",
    "serenity/http",
    "serenity/unstable_discord_api"
]
monitoring = ["prometheus", "hyper"]
reporting = ["reqwest", "url"]

[dependencies]

tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread", "time", "fs"] }
rusqlite = { version = "0.25", features = ["bundled", "backup"] }
r2d2 = "0.8"
r2d2_sqlite = "0.18"
once_cell = "1.4"
regex = { version = "1.3", optional = true }
chrono = "0.4"
indoc = { version = "1.0", optional = true }
log = { version = "0.4", features = ["std", "serde"] }
simplelog = "0.10"
prometheus = { version = "0.12", optional = true }
hyper = { version = "0.14", features = ["server"], optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", optional = true }
config = { version = "0.11", default-features = false, features = ["toml"] }
url = { version = "2.2", features = ["serde"], optional = true }
anyhow = "1.0"
futures-util = "0.3"
tinyvec = { version = "1.5", features = ["alloc"] }
rand = "0.7"

[dependencies.serenity]
version = "0.10"
default-features = false
features = ["model", "rustls_backend"]

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["blocking", "rustls-tls", "json"]
optional = true
