services:
  highlights:
    image: thatsnomoon/highlights:2.0.0
    networks:
      - net
    secrets:
      - highlights-config
    environment:
      HIGHLIGHTS_CONFIG: "/run/secrets/highlights-config"
      HIGHLIGHTS_LOGGING.JAEGER: "jaeger-agent:6831"
    volumes:
      - "highlights-data:/opt/highlights/data"
    depends_on:
      jaeger-agent:
        condition: service_started
    restart: unless-stopped

  jaeger-agent:
    image: jaegertracing/jaeger-agent:1.34
    networks:
      - net
    command: "--reporter.grpc.host-port=jaeger-collector:14250"
    depends_on:
      jaeger-collector:
        condition: service_started
    restart: unless-stopped

  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.34
    networks:
      - net
    environment:
      SPAN_STORAGE_TYPE: "cassandra"
      CASSANDRA_SERVERS: "cassandra"
      CASSANDRA_KEYSPACE: "jaeger_v1_dc1"
    depends_on:
      cassandra-setup:
        condition: service_completed_successfully
    restart: unless-stopped

  jaeger-query:
    image: jaegertracing/jaeger-query:1.34
    networks:
      - net
    ports:
      - "16686:16686"
    environment:
      SPAN_STORAGE_TYPE: "cassandra"
      CASSANDRA_SERVERS: "cassandra"
      CASSANDRA_KEYSPACE: "jaeger_v1_dc1"
    depends_on:
      cassandra-setup:
        condition: service_completed_successfully
    restart: unless-stopped

  cassandra-setup:
    image: thatsnomoon/highlights-jaeger-cassandra-setup:1.0.0
    networks:
      - net
    environment:
      MODE: "prod"
      DATACENTER: "dc1"
      REPLICATION_FACTOR: 1
    depends_on:
      cassandra:
        condition: service_healthy

  cassandra:
    image: cassandra:4.0
    networks:
      - net
    volumes:
      - "cassandra-data:/opt/cassandra/data"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "show version;"]
      interval: 30s
      timeout: 10s
    restart: unless-stopped


secrets:
  highlights-config:
    file: "./config.toml"

networks:
  net: {}

volumes:
  highlights-data:
  cassandra-data:
