# All fields other than bot.token and bot.application_id are optional
# Defaults shown below

[bot]
# Discord bot token
token = "..."
# Discord application (not bot account!) ID
application_id = "..."
# Disables sharing the bot invite link in about command
private = false

[behavior]
# Maximum amount of keywords users can subscribe to
max_keywords = 100
# Amount of seconds to wait for activity before sending a notification
patience_seconds = 120

[logging]
# Discord webhook to send errors and panics to
#webhook = "..."
# IP and port to Jaeger agent
#jaeger = "..."
# Ratio of traces to sample when monitoring with Jaeger, between 0.0 and 1.0
sample_ratio = 1.0
# Default log level for entire application
level = "WARN"
# Whether or not to use ANSI color codes (may not work on Windows)
color = true
[logging.filters]
# The `highlights` crate will log at INFO instead
highlights = "INFO"

[database]
# The folder where database and backups are stored
path = "./data"
# Whether to automatically backup database
backup = true
