# All fields other than bot.token and bot.application_id are optional
# Defaults shown below

[bot]
# Discord bot token
#token = "..."
# Discord application (not bot account!) ID
#application_id = "..."
# Disables sharing the bot invite link in about command
private = false

[behavior]
# Maximum amount of keywords users can subscribe to
max_keywords = 100
# Amount of seconds to wait for activity before sending a notification
patience_seconds = 120

[logging]
# Discord webhook to send errors and panics to
#webhook = "..."
# IP and port to prometheus monitoring server
#prometheus = "..."
# Default log level for entire application
level = "WARN"
[logging.filters]
# The `highlights` crate will log at INFO instead
highlights = "INFO"

[database]
# The folder where database and backups are stored
path = "./data"
# Whether to automatically backup database
backup = true
