# All fields other than bot.token and bot.application_id are optional
# Defaults shown below

[bot]
# Discord bot token
token = "..."
# Discord application (not bot account!) ID
application_id = "..."
# Disables sharing the bot invite link in about command
private = false

[behavior]
# Maximum amount of keywords users can subscribe to
max_keywords = 100
# Amount of time to wait for activity before sending a notification
# Other examples: "1m 30sec", "5minutes"
# See https://docs.rs/humantime/latest/humantime/fn.parse_duration.html for complete list
patience = "2min"
# Amount of time to leave notifications visible
# This uses the same format as patience
# Other examples: "1y", "90d", "1M" (one month)
#notification_lifetime = "1month"

[logging]
# Discord webhook to send errors and panics to
#webhook = "..."
# IP and port to Jaeger agent
#jaeger = "..."
# Ratio of traces to sample when monitoring with Jaeger, between 0.0 and 1.0
sample_ratio = 1.0
# Default log level for entire application
level = "WARN"
# Whether or not to use ANSI color codes (may not work on Windows)
color = true
# Format of standard output logging (can be "compact", "pretty", or "json")
format = "compact"
[logging.filters]
# The `highlights` crate will log at INFO instead
highlights = "INFO"

[database]
# The folder where the SQLite database and backups are stored
path = "./data"
# Database connection URL for use with PostgreSQL (or SQLite, if desired.
# Backups cannot be done using an SQLite URL.).
#url = "postgres://username:password@host:port/database"
# Whether to automatically backup SQLite database
backup = true
