#!/bin/sh

# remove changes that won't be in the commit as applied
git stash push -q --include-untracked --keep-index

cargo fmt -- --check
FMT_RESULT=$?

cargo clippy -- --deny warnings
CLIPPY_RESULT=$?

if [[ "$FMT_RESULT" -eq 0 && "$CLIPPY_RESULT" -eq 0 ]]; then
	git stash pop -q
else
	exit 1
fi

exit 0
